### ISSUE TITLE
I am getting `safety_check: error: Unsupported mix of pyproject.toml & requirements files found` starting in 1.3.0

### ISSUE THREAD

**Issue by masasin** [Lucas-C/pre-commit-hooks-safety#32]
Hello!

Since 1.3.0, I've been getting this error:

```
safety_check: error: Unsupported mix of pyproject.toml & requirements files found
```

For one of the projects that gave me this error, safety helpfully listed the files that were affected. It turned out that there was a requirements folder in the documentation containing markdown files. I managed to fix it by passing `files: pyproject.toml`.

For the other project, there is no file with requirements in the full path, and passing `files: pyproject.toml` doesn't do anything either.

**Comment by Lucas-C** [comment]
Thank you for reporting this.

I have just slightly improved the error message on the `master` branch of this repo, could you try using this version and retry?

```yaml
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: master
    hooks:
    -   id: python-safety-dependencies-check
```
