### ISSUE TITLE
Error: No such option: --disable-telemetry Did you mean --disable-optional-telemetry?

### ISSUE THREAD

**Issue by AlirezaSoltaniJazi** [Lucas-C/pre-commit-hooks-safety#48]
Hi,
I hope you're doing well.
I'm using this config:
```
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.1
    hooks:
    -   id: python-safety-dependencies-check
        name: Check dependencies for vulnerability
        files: requirements*
        args: ["--disable-telemetry"]
```
but I got this error:
```
Error: No such option: --disable-telemetry Did you mean --disable-optional-telemetry?
```
